export const ACTION_TYPE = {
	SET_USER: 'SET_USER',
	LOGOUT: 'LOGOUT',
	SET_CONFECTION_DATA: 'SET_CONFECTION_DATA',
	SET_CART_DATA: 'SET_CART_DATA',

	// FETCH_CART_REQUEST : 'FETCH_CART_REQUEST',
	// FETCH_CART_SUCCESS : 'FETCH_CART_SUCCESS',
	// FETCH_CART_FAILURE : 'FETCH_CART_FAILURE',

	// OPEN_MODAL: 'OPEN_MODAL',
	// CLOSE_MODAL: 'CLOSE_MODAL',
	// RESET_POST_DATA: 'RESET_POST_DATA',

	LOAD_CART: 'LOAD_CART',
	ADD_TO_CART: 'ADD_TO_CART',
	UPDATE_CART: 'UPDATE_CART',
	DELETE_FROM_CART: 'DELETE_FROM_CART',
};
