export const ACTION_TYPE = {
	SET_USER: 'SET_USER',
	LOGOUT: 'LOGOUT',
	SET_CONFECTION_DATA: 'SET_CONFECTION_DATA',
	SET_CART_DATA: 'SET_CART_DATA',

	// FETCH_CART_REQUEST : 'FETCH_CART_REQUEST',
	// FETCH_CART_SUCCESS : 'FETCH_CART_SUCCESS',
	// FETCH_CART_FAILURE : 'FETCH_CART_FAILURE',

	// OPEN_MODAL: 'OPEN_MODAL',
	// CLOSE_MODAL: 'CLOSE_MODAL',
	// RESET_POST_DATA: 'RESET_POST_DATA',
};
